# Numpy

In [ ]:
import numpy as np


In [1]:
my_arr = np.arange(1000000)

In [2]:
my_arr

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [3]:
my_list = list(range(1000000))

In [4]:
%time for _ in range(10): my_arr2 = my_arr *2

Wall time: 21.3 ms


In [5]:
%time for _ in range(10):my_list2 = [x * 2 for x in my_list]

Wall time: 807 ms


In [6]:
my_arr2

array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

In [7]:
my_list2

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

In [10]:
# Generate some dandom data

data = np.random.randn(2,3)

In [11]:
data

array([[ 0.46673336, -2.16968484, -1.66889035],
       [ 0.82307425,  0.23672283, -0.72906897]])

In [12]:
data *10

array([[  4.66733364, -21.69684842, -16.68890345],
       [  8.23074248,   2.36722827,  -7.2906897 ]])

In [13]:
data2 = [[1,2,3,4],[5,6,7,8]]

In [14]:
arr2 = np.array(data2)

In [15]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
np.arange(120)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119])

In [19]:
d  = np.array(120)

In [20]:
d


array(120)

In [24]:
arr = np.empty((8, 4))



In [25]:
 for i in range(8):
    arr[i] = i

In [26]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [28]:
arr[[3,4,5,1]]

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [1., 1., 1., 1.]])

In [29]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [31]:
# select specific value

arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [32]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [36]:
# arrange sort
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [37]:
# profuct

arr = np.random.randn(6, 3)

In [38]:
arr

array([[ 1.7817046 , -0.22282646, -0.58173439],
       [ 0.42733817, -0.12420562, -0.22801107],
       [-0.90842273,  0.75807775, -0.94594953],
       [-2.68675379, -1.30955549,  0.00922252],
       [ 1.03922414, -0.62669673, -2.52762187],
       [ 0.67159421,  0.3535902 , -0.44666705]])

In [39]:
arr.T

array([[ 1.7817046 ,  0.42733817, -0.90842273, -2.68675379,  1.03922414,
         0.67159421],
       [-0.22282646, -0.12420562,  0.75807775, -1.30955549, -0.62669673,
         0.3535902 ],
       [-0.58173439, -0.22801107, -0.94594953,  0.00922252, -2.52762187,
        -0.44666705]])

In [40]:
np.dot(arr.T,arr)

array([[12.93199258,  1.96590017, -3.22611793],
       [ 1.96590017,  2.87247096,  0.85488063],
       [-3.22611793,  0.85488063,  7.87369329]])

In [4]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [6]:
result = [(x if c else y) for x,y,c in zip(xarr,yarr,cond)]

In [7]:
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [8]:
result = np.where(cond,xarr,yarr)

In [9]:
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

#### Linear Algebra

In [11]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])

In [12]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [13]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [14]:
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

#### Pseudorandom Number Generation

In [15]:
samples = np.random.normal(size=(4, 4))

In [16]:
samples

array([[-0.2571016 ,  2.34764625, -0.65223765,  0.52850516],
       [-1.09112755,  0.40276305,  1.41515407, -0.92040011],
       [-0.7216261 ,  1.16815846,  0.92097641, -0.58847461],
       [ 0.15036442,  2.92116115,  0.62012296,  0.00436872]])

In [17]:
from random import normalvariate

In [18]:
N= 1000000

In [22]:
%timeit samples = [normalvariate(0, 1) for _ in range(N)]

951 ms ± 62.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [20]:
%timeit np.random.normal(size=N)

28.3 ms ± 499 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [28]:
a = np.random.seed(1234)

In [33]:
rng.randn(10)

NameError: name 'rng' is not defined